### Multilayer Perceptron (MLP) for multi-class softmax classification (Keras Tensorflow)

In [1]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
# from keras.optimizers import SGD
from keras.utils import np_utils
from tensorflow.keras.optimizers import SGD
from sklearn.model_selection import train_test_split

np.random.seed(7)

# Load the data
X = np.load('feat.npy')
y = np.load('label.npy').ravel() 

number_of_features = len(X[1]) #This has 23 features
number_of_classes = 3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0) 

#model
model = Sequential()

model.add(Dense(512, input_dim=number_of_features, activation='relu')) 
model.add(Dropout(0.5))

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(number_of_classes, activation='softmax'))



2022-11-15 10:07:53.879889: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               12288     
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_1 (Dense)             (None, 512)               262656    
                                                                 
 dropout_1 (Dropout)         (None, 512)               0         
                                                                 
 dense_2 (Dense)             (None, 3)                 1539      
                                                                 
Total params: 276,483
Trainable params: 276,483
Non-trainable params: 0
_________________________________________________________________


In [3]:

sgd = SGD(learning_rate=0.01, decay=1e-6, momentum=0.9, nesterov=True)
rmsprop = 'rmsprop'
adam = 'adam'
model.compile(loss='categorical_crossentropy',
              optimizer= rmsprop,
              metrics=['accuracy'])

y_train = keras.utils.np_utils.to_categorical(y_train-1, num_classes= number_of_classes) 
y_test = keras.utils.np_utils.to_categorical(y_test-1, num_classes= number_of_classes)



# Epoch-300 , batch_size = 64  

In [4]:
model.fit(X_train, y_train, epochs=300, batch_size=64) #batch 32, 64, 128, 256, 512
score, acc = model.evaluate(X_test, y_test, batch_size=64)

Epoch 1/300
16/16 [==============================] - 1s 6ms/step - loss: 27.6058 - accuracy: 0.4006
Epoch 2/300
16/16 [==============================] - 0s 6ms/step - loss: 11.1179 - accuracy: 0.4538
Epoch 3/300
16/16 [==============================] - 0s 7ms/step - loss: 6.9264 - accuracy: 0.5040
Epoch 4/300
16/16 [==============================] - 0s 6ms/step - loss: 4.5043 - accuracy: 0.5231
Epoch 5/300
16/16 [==============================] - 0s 6ms/step - loss: 2.7618 - accuracy: 0.5552
Epoch 6/300
16/16 [==============================] - 0s 13ms/step - loss: 1.8427 - accuracy: 0.5793
Epoch 7/300
16/16 [==============================] - 0s 9ms/step - loss: 1.3568 - accuracy: 0.5863
Epoch 8/300
16/16 [==============================] - 0s 8ms/step - loss: 1.2179 - accuracy: 0.5873
Epoch 9/300
16/16 [==============================] - 0s 8ms/step - loss: 1.0035 - accuracy: 0.6285
Epoch 10/300
16/16 [==============================] - 0s 6ms/step - loss: 0.8767 - accuracy: 0.6637
Epoch 

Epoch 83/300
16/16 [==============================] - 0s 8ms/step - loss: 0.1850 - accuracy: 0.9167
Epoch 84/300
16/16 [==============================] - 0s 5ms/step - loss: 0.1784 - accuracy: 0.9227
Epoch 85/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1834 - accuracy: 0.9207
Epoch 86/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1907 - accuracy: 0.9157
Epoch 87/300
16/16 [==============================] - 0s 8ms/step - loss: 0.1771 - accuracy: 0.9237
Epoch 88/300
16/16 [==============================] - 0s 9ms/step - loss: 0.1700 - accuracy: 0.9267
Epoch 89/300
16/16 [==============================] - 0s 8ms/step - loss: 0.1669 - accuracy: 0.9207
Epoch 90/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1736 - accuracy: 0.9327
Epoch 91/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1865 - accuracy: 0.9267
Epoch 92/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1715 - accuracy: 0.9267


16/16 [==============================] - 0s 6ms/step - loss: 0.1824 - accuracy: 0.9317
Epoch 165/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1622 - accuracy: 0.9277
Epoch 166/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1262 - accuracy: 0.9508
Epoch 167/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1488 - accuracy: 0.9398
Epoch 168/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1396 - accuracy: 0.9438
Epoch 169/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1633 - accuracy: 0.9428
Epoch 170/300
16/16 [==============================] - 0s 7ms/step - loss: 0.1304 - accuracy: 0.9528
Epoch 171/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1497 - accuracy: 0.9347
Epoch 172/300
16/16 [==============================] - 0s 5ms/step - loss: 0.1399 - accuracy: 0.9428
Epoch 173/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1199 - accuracy: 0.9448
Epoc

16/16 [==============================] - 0s 7ms/step - loss: 0.1093 - accuracy: 0.9558
Epoch 246/300
16/16 [==============================] - 0s 8ms/step - loss: 0.1171 - accuracy: 0.9498
Epoch 247/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1359 - accuracy: 0.9458
Epoch 248/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1077 - accuracy: 0.9508
Epoch 249/300
16/16 [==============================] - 0s 7ms/step - loss: 0.1168 - accuracy: 0.9538
Epoch 250/300
16/16 [==============================] - 0s 7ms/step - loss: 0.1134 - accuracy: 0.9558
Epoch 251/300
16/16 [==============================] - 0s 7ms/step - loss: 0.1244 - accuracy: 0.9478
Epoch 252/300
16/16 [==============================] - 0s 7ms/step - loss: 0.1442 - accuracy: 0.9478
Epoch 253/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1043 - accuracy: 0.9448
Epoch 254/300
16/16 [==============================] - 0s 6ms/step - loss: 0.1171 - accuracy: 0.9518
Epoc

In [5]:
print ('Test score:', score)
print('Test accuracy:', acc)

Test score: 0.3853221833705902
Test accuracy: 0.9415887594223022


In [6]:
import pickle
filename = 'mlp/mlp_300_64.sav'
pickle.dump(model, open(filename, 'wb'))

2022-11-15 10:08:29.164696: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: ram://b5b09351-2994-4adf-a814-ca3661db8658/assets


In [7]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)
print(result)

[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [8.6404628e-01 1.3595240e-01 1.2988644e-06]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 ...
 [9.8610538e-01 1.3894674e-02 1.9644220e-11]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [5.7721678e-23 1.0000000e+00 2.2713532e-33]]


# Epochs = 300  , batch_size=128

In [8]:
model.fit(X_train, y_train, epochs=300, batch_size=128) #batch 32, 64, 128, 256, 512
score, acc = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/300
8/8 [==============================] - 0s 7ms/step - loss: 0.1059 - accuracy: 0.9578
Epoch 2/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0696 - accuracy: 0.9709
Epoch 3/300
8/8 [==============================] - 0s 7ms/step - loss: 0.1055 - accuracy: 0.9578
Epoch 4/300
8/8 [==============================] - 0s 29ms/step - loss: 0.1140 - accuracy: 0.9508
Epoch 5/300
8/8 [==============================] - 0s 10ms/step - loss: 0.1120 - accuracy: 0.9528
Epoch 6/300
8/8 [==============================] - 0s 9ms/step - loss: 0.0978 - accuracy: 0.9639
Epoch 7/300
8/8 [==============================] - 0s 10ms/step - loss: 0.0847 - accuracy: 0.9669
Epoch 8/300
8/8 [==============================] - 0s 7ms/step - loss: 0.1110 - accuracy: 0.9649
Epoch 9/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0639 - accuracy: 0.9669
Epoch 10/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0859 - accuracy: 0.9649
Epoch 11/300
8/8 [========

8/8 [==============================] - 0s 10ms/step - loss: 0.0813 - accuracy: 0.9679
Epoch 85/300
8/8 [==============================] - 0s 7ms/step - loss: 0.1037 - accuracy: 0.9618
Epoch 86/300
8/8 [==============================] - 0s 9ms/step - loss: 0.1047 - accuracy: 0.9528
Epoch 87/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0707 - accuracy: 0.9749
Epoch 88/300
8/8 [==============================] - 0s 7ms/step - loss: 0.1029 - accuracy: 0.9689
Epoch 89/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0798 - accuracy: 0.9639
Epoch 90/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0758 - accuracy: 0.9679
Epoch 91/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0777 - accuracy: 0.9679
Epoch 92/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0987 - accuracy: 0.9588
Epoch 93/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0741 - accuracy: 0.9729
Epoch 94/300
8/8 [==============

Epoch 167/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0736 - accuracy: 0.9709
Epoch 168/300
8/8 [==============================] - 0s 6ms/step - loss: 0.0857 - accuracy: 0.9629
Epoch 169/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0799 - accuracy: 0.9739
Epoch 170/300
8/8 [==============================] - 0s 9ms/step - loss: 0.0615 - accuracy: 0.9729
Epoch 171/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0698 - accuracy: 0.9769
Epoch 172/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0721 - accuracy: 0.9759
Epoch 173/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0925 - accuracy: 0.9659
Epoch 174/300
8/8 [==============================] - 0s 10ms/step - loss: 0.0712 - accuracy: 0.9739
Epoch 175/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0499 - accuracy: 0.9769
Epoch 176/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0594 - accuracy: 0.9759
Epoch 177

8/8 [==============================] - 0s 8ms/step - loss: 0.0761 - accuracy: 0.9739
Epoch 250/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0633 - accuracy: 0.9749
Epoch 251/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0778 - accuracy: 0.9669
Epoch 252/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0500 - accuracy: 0.9789
Epoch 253/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0579 - accuracy: 0.9759
Epoch 254/300
8/8 [==============================] - 0s 7ms/step - loss: 0.0716 - accuracy: 0.9759
Epoch 255/300
8/8 [==============================] - 0s 11ms/step - loss: 0.0760 - accuracy: 0.9719
Epoch 256/300
8/8 [==============================] - 0s 9ms/step - loss: 0.0714 - accuracy: 0.9729
Epoch 257/300
8/8 [==============================] - 0s 9ms/step - loss: 0.0580 - accuracy: 0.9779
Epoch 258/300
8/8 [==============================] - 0s 8ms/step - loss: 0.0526 - accuracy: 0.9779
Epoch 259/300
8/8 [====

In [9]:
print ('Test score:', score)
print('Test accuracy:', acc)

Test score: 0.6060696840286255
Test accuracy: 0.9322429895401001


In [10]:
import pickle
filename = 'mlp/mlp_300_128.sav'
pickle.dump(model, open(filename, 'wb'))

INFO:tensorflow:Assets written to: ram://c744c668-17d1-4484-a63a-4d2394a99b9c/assets


In [11]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)
print(result)

[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [9.5400739e-01 4.5992550e-02 2.1836108e-08]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 ...
 [9.9609560e-01 3.9043969e-03 3.7743090e-17]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [6.3941390e-36 1.0000000e+00 0.0000000e+00]]


# Epochs = 300 , batch_size = 32 

In [12]:
model.fit(X_train, y_train, epochs=300, batch_size=32) #batch 32, 64, 128, 256, 512
score, acc = model.evaluate(X_test, y_test, batch_size=32)

Epoch 1/300
32/32 [==============================] - 0s 5ms/step - loss: 0.0985 - accuracy: 0.9689
Epoch 2/300
32/32 [==============================] - 0s 7ms/step - loss: 0.1191 - accuracy: 0.9629
Epoch 3/300
32/32 [==============================] - 0s 5ms/step - loss: 0.0759 - accuracy: 0.9719
Epoch 4/300
32/32 [==============================] - 0s 4ms/step - loss: 0.0986 - accuracy: 0.9588
Epoch 5/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1332 - accuracy: 0.9608
Epoch 6/300
32/32 [==============================] - 0s 6ms/step - loss: 0.1007 - accuracy: 0.9598
Epoch 7/300
32/32 [==============================] - 0s 6ms/step - loss: 0.1294 - accuracy: 0.9568
Epoch 8/300
32/32 [==============================] - 0s 6ms/step - loss: 0.0769 - accuracy: 0.9739
Epoch 9/300
32/32 [==============================] - 0s 5ms/step - loss: 0.0857 - accuracy: 0.9649
Epoch 10/300
32/32 [==============================] - 0s 5ms/step - loss: 0.0879 - accuracy: 0.9719
Epoch 11/

Epoch 83/300
32/32 [==============================] - 0s 7ms/step - loss: 0.1192 - accuracy: 0.9689
Epoch 84/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1428 - accuracy: 0.9538
Epoch 85/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1144 - accuracy: 0.9608
Epoch 86/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1110 - accuracy: 0.9618
Epoch 87/300
32/32 [==============================] - 0s 6ms/step - loss: 0.1068 - accuracy: 0.9669
Epoch 88/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1237 - accuracy: 0.9669
Epoch 89/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1406 - accuracy: 0.9679
Epoch 90/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1193 - accuracy: 0.9558
Epoch 91/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1136 - accuracy: 0.9639
Epoch 92/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1233 - accuracy: 0.9679


32/32 [==============================] - 0s 4ms/step - loss: 0.0844 - accuracy: 0.9699
Epoch 165/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1494 - accuracy: 0.9629
Epoch 166/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1116 - accuracy: 0.9649
Epoch 167/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1027 - accuracy: 0.9669
Epoch 168/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1212 - accuracy: 0.9669
Epoch 169/300
32/32 [==============================] - 0s 4ms/step - loss: 0.1166 - accuracy: 0.9679
Epoch 170/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1116 - accuracy: 0.9739
Epoch 171/300
32/32 [==============================] - 0s 5ms/step - loss: 0.1161 - accuracy: 0.9669
Epoch 172/300
32/32 [==============================] - 0s 8ms/step - loss: 0.1413 - accuracy: 0.9669
Epoch 173/300
32/32 [==============================] - 0s 10ms/step - loss: 0.0675 - accuracy: 0.9679
Epo

32/32 [==============================] - 0s 8ms/step - loss: 0.0841 - accuracy: 0.9719
Epoch 246/300
32/32 [==============================] - 0s 8ms/step - loss: 0.1068 - accuracy: 0.9709
Epoch 247/300
32/32 [==============================] - 0s 8ms/step - loss: 0.0952 - accuracy: 0.9709
Epoch 248/300
32/32 [==============================] - 0s 8ms/step - loss: 0.1349 - accuracy: 0.9669
Epoch 249/300
32/32 [==============================] - 0s 8ms/step - loss: 0.0985 - accuracy: 0.9709
Epoch 250/300
32/32 [==============================] - 0s 7ms/step - loss: 0.1214 - accuracy: 0.9669
Epoch 251/300
32/32 [==============================] - 0s 10ms/step - loss: 0.0871 - accuracy: 0.9649
Epoch 252/300
32/32 [==============================] - 0s 9ms/step - loss: 0.1507 - accuracy: 0.9669
Epoch 253/300
32/32 [==============================] - 0s 11ms/step - loss: 0.1139 - accuracy: 0.9659
Epoch 254/300
32/32 [==============================] - 0s 8ms/step - loss: 0.1107 - accuracy: 0.9689
Ep

In [13]:
print ('Test score:', score)
print('Test accuracy:', acc)

Test score: 0.8866744637489319
Test accuracy: 0.9182242751121521


In [14]:
model.evaluate(X_test, y_test, batch_size=256)

2/2 [==============================] - 0s 4ms/step - loss: 0.8867 - accuracy: 0.9182


[0.8866744637489319, 0.9182242751121521]

In [15]:
import pickle
filename = 'mlp/mlp_300_32.sav'
pickle.dump(model, open(filename, 'wb'))

INFO:tensorflow:Assets written to: ram://a5e969f2-424e-42bc-b569-9947e68887f3/assets


In [16]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)
print(result)

[[0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [9.9999452e-01 5.5402365e-06 9.0014647e-20]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]
 ...
 [9.9772447e-01 2.2754981e-03 2.2433949e-15]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00]]


# Model Testing 


In [28]:
import pickle 
model_test = pickle.load(open('mlp/mlp_300_32.sav', 'rb'))


In [29]:
import glob
import os
import librosa
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import specgram
import soundfile as sf
import numpy as np 

##Return audio features 
def feature_extraction(file_name):
    #X, sample_rate = sf.read(file_name, dtype='float32')
    X , sample_rate = librosa.load(file_name, sr=None) 
    if X.ndim > 1:
        X = X[:,0]
    X = X.T
    
    ## stFourier Transform
    stft = np.abs(librosa.stft(X))
            
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=20).T, axis=0) 
    rmse = np.mean(librosa.feature.rms(y=X).T, axis=0) 
    spectral_flux = np.mean(librosa.onset.onset_strength(y=X, sr=sample_rate).T, axis=0) 
    zcr = np.mean(librosa.feature.zero_crossing_rate(y=X).T, axis=0)
    
    #mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T, axis=0) #Returns 128 values
    #chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T, axis=0) #Returns 12 values
    #contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T, axis=0) #Returns 7 values
    #tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=sample_rate).T, axis=0)
    
    ##Return computed audio features
    return mfccs, rmse, spectral_flux, zcr
    
    


In [30]:
# feature_predict = feature_extraction(file_path)

In [31]:
predict_path = 'audio-data/002 - Intermediate /Avalinguo - Alan and Eduardo segment 30 - E.mp3'
n_mfccs = 20 
number_of_features = 3 + n_mfccs
features = np.empty((0,number_of_features))
mfccs, rmse, spectral_flux, zcr = feature_extraction(predict_path)
extracted_features = np.hstack([mfccs, rmse, spectral_flux, zcr])
features_predict = np.vstack([features, extracted_features])
result = model_test.predict(features_predict)

In [32]:
result[0]

array([1.6808353e-07, 9.9999964e-01, 2.8777660e-07], dtype=float32)

In [33]:
i = np.argmax(result[0])
if(i==0):
    print('LOW')
elif(i==1):
    print('INTERMEDIATE')
else:
    print('HIGH')

INTERMEDIATE


# Live Audio Capture and Classification

In [61]:
import sounddevice as sd
from scipy.io.wavfile import write
import wavio as wv
import numpy as np
from pydub import AudioSegment

  
freq = 44100
  
duration = 10
  
recording = sd.rec(int(duration * freq), 
                   samplerate=freq, channels=1)
  
sd.wait()
    
wv.write("recording.wav", recording, freq, sampwidth=2)

sound = AudioSegment.from_wav('recording.wav')

sound.export('myfile.mp3', format='mp3')
sound = AudioSegment.from_wav('recording.wav')
 
sound.export('recording.mp3', format='mp3')

<_io.BufferedRandom name='recording.mp3'>

In [47]:
def feature_out(predict_path):
    n_mfccs = 20 
    number_of_features = 3 + n_mfccs
    features = np.empty((0,number_of_features))
    mfccs, rmse, spectral_flux, zcr = feature_extraction(predict_path)
    extracted_features = np.hstack([mfccs, rmse, spectral_flux, zcr])
    features_predict = np.vstack([features, extracted_features])
    return features_predict

In [62]:
predict_path = 'recording.wav'
features_predict = feature_out(predict_path)
result = model_test.predict(features_predict)


In [63]:
result[0]

array([0., 1., 0.], dtype=float32)

In [64]:
i = np.argmax(result[0])
if(i==0):
    print('LOW')
elif(i==1):
    print('INTERMEDIATE')
else:
    print('HIGH')

INTERMEDIATE
